import { useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { SelectField } from "@/components/common";
import { centsToAmount, formatCents, parseAmountToCents } from "@/features/pricing/lib/money";
import { QUOTE_LINE_KIND_LABELS } from "../types";
import type { QuoteLineItem, QuoteLineKind } from "../types";

const KIND_OPTIONS = Object.entries(QUOTE_LINE_KIND_LABELS).map(([value, label]) => ({
  value,
  label,
}));

type LineDraft = {
  label: string;
  detail: string;
  kind: QuoteLineKind;
  quantity: string;
  amount: string;
};

const EMPTY_DRAFT: LineDraft = {
  label: "",
  detail: "",
  kind: "custom",
  quantity: "1",
  amount: "0.00",
};

/**
 * Editable line table for a quote. Every line generated by the pricing engine
 * can be renamed, re-priced, re-quantified or removed, and extra charges or
 * discounts can be added by hand.
 */
export function QuoteLineEditor({
  lines,
  currency,
  readOnly,
  onUpdate,
  onDelete,
  onAdd,
  busy,
}: {
  lines: QuoteLineItem[];
  currency: string;
  readOnly?: boolean;
  onUpdate: (id: string, values: Partial<QuoteLineItem>) => void;
  onDelete: (id: string) => void;
  onAdd: (values: {
    label: string;
    detail: string | null;
    kind: QuoteLineKind;
    quantity: number;
    unitCents: number;
  }) => void;
  busy?: boolean;
}) {
  const [draft, setDraft] = useState<LineDraft>(EMPTY_DRAFT);
  const set = (patch: Partial<LineDraft>) => setDraft((prev) => ({ ...prev, ...patch }));

  const submitDraft = () => {
    if (!draft.label.trim()) return;
    onAdd({
      label: draft.label.trim(),
      detail: draft.detail.trim() || null,
      kind: draft.kind,
      quantity: Math.max(1, Number.parseInt(draft.quantity, 10) || 1),
      unitCents: parseAmountToCents(draft.amount),
    });
    setDraft(EMPTY_DRAFT);
  };

  return (
    <div className="space-y-3">
      <div className="hidden gap-3 px-1 text-xs text-muted-foreground sm:grid sm:grid-cols-[1fr_120px_80px_110px_40px]">
        <span>Description</span>
        <span>Type</span>
        <span className="text-right">Qty</span>
        <span className="text-right">Unit</span>
        <span />
      </div>

      {lines.map((line) => (
        <div
          key={line.id}
          className="grid gap-3 rounded-xl border border-border p-3 sm:grid-cols-[1fr_120px_80px_110px_40px] sm:items-center sm:border-0 sm:p-1"
        >
          <div className="space-y-1">
            <Input
              value={line.label}
              disabled={readOnly}
              onChange={(event) => onUpdate(line.id, { label: event.target.value })}
              onBlur={(event) =>
                onUpdate(line.id, { label: event.target.value, __commit: true } as never)
              }
            />
            {line.detail && (
              <p className="px-1 text-xs text-muted-foreground">{line.detail}</p>
            )}
          </div>

          <SelectField
            value={line.kind}
            options={KIND_OPTIONS}
            disabled={readOnly}
            onChange={(value) =>
              onUpdate(line.id, { kind: value as QuoteLineKind, __commit: true } as never)
            }
          />

          <Input
            type="number"
            min={1}
            className="text-right"
            defaultValue={line.quantity}
            disabled={readOnly}
            onBlur={(event) =>
              onUpdate(line.id, {
                quantity: Math.max(1, Number.parseInt(event.target.value, 10) || 1),
                __commit: true,
              } as never)
            }
          />

          <Input
            className="text-right"
            defaultValue={centsToAmount(line.unitCents)}
            disabled={readOnly}
            onBlur={(event) =>
              onUpdate(line.id, {
                unitCents: parseAmountToCents(event.target.value),
                __commit: true,
              } as never)
            }
          />

          <div className="flex items-center justify-between gap-2 sm:justify-end">
            <span className="text-sm sm:hidden">
              {formatCents(line.amountCents, currency)}
            </span>
            {!readOnly && (
              <Button
                variant="ghost"
                size="icon"
                aria-label={`Remove ${line.label}`}
                disabled={busy}
                onClick={() => onDelete(line.id)}
              >
                <Trash2 className="h-4 w-4" />
              </Button>
            )}
          </div>
        </div>
      ))}

      {!readOnly && (
        <div className="grid gap-3 rounded-xl border border-dashed border-border p-3 sm:grid-cols-[1fr_120px_80px_110px_40px] sm:items-center">
          <Input
            placeholder="Add a line — e.g. Cake stand hire"
            value={draft.label}
            onChange={(event) => set({ label: event.target.value })}
          />
          <SelectField
            value={draft.kind}
            options={KIND_OPTIONS}
            onChange={(value) => set({ kind: value as QuoteLineKind })}
          />
          <Input
            type="number"
            min={1}
            className="text-right"
            value={draft.quantity}
            onChange={(event) => set({ quantity: event.target.value })}
          />
          <Input
            className="text-right"
            value={draft.amount}
            onChange={(event) => set({ amount: event.target.value })}
          />
          <Button
            size="icon"
            aria-label="Add line"
            disabled={!draft.label.trim() || busy}
            onClick={submitDraft}
          >
            <Plus className="h-4 w-4" />
          </Button>
        </div>
      )}
    </div>
  );
}
