import { useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";
import { centsToAmount, formatCents, parseAmountToCents } from "@/features/pricing/lib/money";
import { QUOTE_LINE_KIND_LABELS } from "../types";
import type { QuoteLineItem, QuoteLineKind } from "../types";

const KIND_ENTRIES = Object.entries(QUOTE_LINE_KIND_LABELS) as [QuoteLineKind, string][];

function KindSelect({
  value,
  disabled,
  onChange,
}: {
  value: QuoteLineKind;
  disabled?: boolean;
  onChange: (value: QuoteLineKind) => void;
}) {
  return (
    <select
      value={value}
      disabled={disabled}
      onChange={(event) => onChange(event.target.value as QuoteLineKind)}
      aria-label="Line type"
      className={cn(
        "h-10 w-full rounded-xl border border-border bg-background px-3 text-sm transition-colors focus:border-primary focus:outline-none",
        disabled && "opacity-60",
      )}
    >
      {KIND_ENTRIES.map(([kind, label]) => (
        <option key={kind} value={kind}>
          {label}
        </option>
      ))}
    </select>
  );
}

type LineDraft = {
  label: string;
  kind: QuoteLineKind;
  quantity: string;
  amount: string;
};

const EMPTY_DRAFT: LineDraft = { label: "", kind: "custom", quantity: "1", amount: "0.00" };

export type QuoteLineEdit = {
  label?: string;
  kind?: QuoteLineKind;
  quantity?: number;
  unitCents?: number;
};

/**
 * Editable line table for a quote. Every line generated by the pricing engine
 * can be renamed, re-priced, re-quantified or removed, and extra charges or
 * discounts can be added by hand.
 */
export function QuoteLineEditor({
  lines,
  currency,
  readOnly,
  onUpdate,
  onDelete,
  onAdd,
  busy,
}: {
  lines: QuoteLineItem[];
  currency: string;
  readOnly?: boolean;
  onUpdate: (id: string, values: QuoteLineEdit) => void;
  onDelete: (id: string) => void;
  onAdd: (values: {
    label: string;
    kind: QuoteLineKind;
    quantity: number;
    unitCents: number;
  }) => void;
  busy?: boolean;
}) {
  const [draft, setDraft] = useState<LineDraft>(EMPTY_DRAFT);
  const set = (patch: Partial<LineDraft>) => setDraft((prev) => ({ ...prev, ...patch }));

  const submitDraft = () => {
    if (!draft.label.trim()) return;
    onAdd({
      label: draft.label.trim(),
      kind: draft.kind,
      quantity: Math.max(1, Number.parseInt(draft.quantity, 10) || 1),
      unitCents: parseAmountToCents(draft.amount),
    });
    setDraft(EMPTY_DRAFT);
  };

  return (
    <div className="space-y-3">
      <div className="hidden gap-3 px-1 text-xs text-muted-foreground sm:grid sm:grid-cols-[1fr_130px_70px_110px_100px_40px]">
        <span>Description</span>
        <span>Type</span>
        <span className="text-right">Qty</span>
        <span className="text-right">Unit</span>
        <span className="text-right">Amount</span>
        <span />
      </div>

      {lines.map((line) => (
        <div
          key={line.id}
          className="grid gap-3 rounded-xl border border-border p-3 sm:grid-cols-[1fr_130px_70px_110px_100px_40px] sm:items-center sm:border-0 sm:p-1"
        >
          <div className="space-y-1">
            <Input
              key={`${line.id}-label`}
              defaultValue={line.label}
              disabled={readOnly}
              onBlur={(event) => {
                const label = event.target.value.trim();
                if (label && label !== line.label) onUpdate(line.id, { label });
              }}
            />
            {line.detail && <p className="px-1 text-xs text-muted-foreground">{line.detail}</p>}
          </div>

          <KindSelect
            value={line.kind}
            disabled={readOnly}
            onChange={(kind) => onUpdate(line.id, { kind })}
          />

          <Input
            key={`${line.id}-qty`}
            type="number"
            min={1}
            className="text-right"
            defaultValue={line.quantity}
            disabled={readOnly}
            onBlur={(event) => {
              const quantity = Math.max(1, Number.parseInt(event.target.value, 10) || 1);
              if (quantity !== line.quantity) onUpdate(line.id, { quantity });
            }}
          />

          <Input
            key={`${line.id}-unit`}
            className="text-right"
            defaultValue={centsToAmount(line.unitCents)}
            disabled={readOnly}
            onBlur={(event) => {
              const unitCents = parseAmountToCents(event.target.value);
              if (unitCents !== line.unitCents) onUpdate(line.id, { unitCents });
            }}
          />

          <span className="text-right text-sm font-medium">
            {formatCents(line.amountCents, currency)}
          </span>

          <div className="flex justify-end">
            {!readOnly && (
              <Button
                variant="ghost"
                size="icon"
                aria-label={`Remove ${line.label}`}
                disabled={busy}
                onClick={() => onDelete(line.id)}
              >
                <Trash2 className="h-4 w-4" />
              </Button>
            )}
          </div>
        </div>
      ))}

      {!readOnly && (
        <div className="grid gap-3 rounded-xl border border-dashed border-border p-3 sm:grid-cols-[1fr_130px_70px_110px_100px_40px] sm:items-center">
          <Input
            placeholder="Add a line — e.g. Cake stand hire"
            value={draft.label}
            onChange={(event) => set({ label: event.target.value })}
          />
          <KindSelect value={draft.kind} onChange={(kind) => set({ kind })} />
          <Input
            type="number"
            min={1}
            className="text-right"
            value={draft.quantity}
            onChange={(event) => set({ quantity: event.target.value })}
          />
          <Input
            className="text-right"
            value={draft.amount}
            onChange={(event) => set({ amount: event.target.value })}
          />
          <span className="hidden sm:block" />
          <Button
            size="icon"
            aria-label="Add line"
            disabled={!draft.label.trim() || busy}
            onClick={submitDraft}
          >
            <Plus className="h-4 w-4" />
          </Button>
        </div>
      )}
    </div>
  );
}
